In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
input = df.drop('Survived', axis = 'columns')

In [5]:
target = df['Survived']

In [15]:
from sklearn.preprocessing import LabelEncoder
l_name = LabelEncoder()
l_sex = LabelEncoder()
l_ticket = LabelEncoder()
l_cabin = LabelEncoder()
l_embarked = LabelEncoder()

In [16]:
input['name_n'] = l_name.fit_transform(input['Name'])
input['sex_n'] = l_sex.fit_transform(input['Sex'])
input['ticket_n'] = l_ticket.fit_transform(input['Ticket'])
input['cabin_n'] = l_cabin.fit_transform(input['Cabin'])
input['embarked_n'] = l_embarked.fit_transform(input['Embarked'])

In [17]:
input

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,name_n,sex_n,ticket_n,cabin_n,embarked_n
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,108,1,523,147,2
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,190,0,596,81,0
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,353,0,669,147,2
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,272,0,49,55,2
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,15,1,472,147,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,548,1,101,147,2
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,303,0,14,30,2
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,413,0,675,147,2
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,81,1,8,60,0
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,220,1,466,147,1

In [35]:
input_n = input.drop(['Name', 'Sex', 'Cabin', 'Embarked', 'Ticket'], axis = 'columns')

In [36]:
input_n

,PassengerId,Pclass,Age,SibSp,Parch,Fare,name_n,sex_n,ticket_n,cabin_n,embarked_n
0,1,3,22.0,1,0,7.2500,108,1,523,147,2
1,2,1,38.0,1,0,71.2833,190,0,596,81,0
2,3,3,26.0,0,0,7.9250,353,0,669,147,2
3,4,1,35.0,1,0,53.1000,272,0,49,55,2
4,5,3,35.0,0,0,8.0500,15,1,472,147,2
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,27.0,0,0,13.0000,548,1,101,147,2
887,888,1,19.0,0,0,30.0000,303,0,14,30,2
888,889,3,NaN,1,2,23.4500,413,0,675,147,2
889,890,1,26.0,0,0,30.0000,81,1,8,60,0
890,891,3,32.0,0,0,7.7500,220,1,466,147,1

In [23]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [24]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [26]:
model.fit(input_n, target)

DecisionTreeClassifier()

In [27]:
model.score(input_n, target)

1.0

In [37]:
model.predict([[1,3,22.0,1,0,7.2500,108,1,523,147,2]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [38]:
model.predict([[4,1,35.0,1,0,53.1000,272,0,49,55,2]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])